### ISSUE TITLE
Models are not getting created

### ISSUE THREAD

**Issue by nmsbane** [testdrivenio/testdriven-app-2.2#14]
Hi Michael, 

I am following your tutorial series and i faced the following issue, 

When `db.init_app(app)` is called, it did not create `User` model in the database. 

Because of this, when i try to post a new entry to route `POST /app/` i am getting internal server. 

I am enjoying learning from your tutorials. Thanks a lot Michael.

**Comment by mjhea0** [comment]
Hi - Please email me - michael at mherman dot org - for support. Thanks!
