### ISSUE TITLE
first react test classname discrepency

### ISSUE THREAD

**Issue by euri10** [testdrivenio/testdriven-app-2.2#17]
p87 the 1st react test tests for the className to be `well` :
`expect(element.get(0).props.className).toBe('well');`

however the UserList component defined just above p83 has the following return method, hence the test failing:
```
return (
<h4
key={user.id}
className="card card-body bg-light"
>{user.username}
</h4>
) 
```

**Comment by mjhea0** [comment]
Nice catch. I'll get this updated. Also, can you email issues directly to me - michael at mherman dot org. Thanks!
